### ISSUE TITLE
Why server don't work?

### ISSUE THREAD

**Issue by gubri** [alphacep/vosk-server#133]
Hello,
have some problem with run server and test.py

Python 3.8.10

anton@anton2:~/vosk-server/websocket$ docker run -p 2700:2700 alphacep/kaldi-ru:latest
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0396459 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:240) Loading i-vector extractor from /opt/vosk-model-ru/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:270) Loading HCLG from /opt/vosk-model-ru/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:285) Loading words from /opt/vosk-model-ru/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading winfo /opt/vosk-model-ru/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:301) Loading RNNLM model from /opt/vosk-model-ru/model/rnnlm/final.raw
anton@anton2:~/vosk-server/websocket$ 

Then

anton@anton2:~/vosk-server/websocket$ ./test.py test.wav
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./test.py", line 8, in run_test
    async with websockets.connect(uri) as websocket:
  File "/home/anton/.local/lib/python3.8/site-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/home/anton/.local/lib/python3.8/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 2700)

Where i can check server status and why server dont work? (as i understand con failed say me about it)

**Comment by nshmyrev** [comment]
Not enough memory probably. It requires 10Gb.

**Comment by gubri** [comment]
Thank you)
Is it possible to run with 8gb?

**Comment by nshmyrev** [comment]
What is your usecase and the hardware you have.

**Comment by nshmyrev** [comment]
Same as #77
