### ISSUE TITLE
Can't run the docker image on an arm64 architecture

### ISSUE THREAD

**Issue by EziamakaNV** [alphacep/vosk-server#147]
Hello,

I tried running the docker image on an arm64 architecture server and this was the response I got

"The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

Is there anyway to get this to run on the platform?

Thank you

**Comment by sskorol** [comment]
Hi, you can try building it on your own or in case if you have GPU, here's a repo: https://github.com/sskorol/vosk-api-gpu

**Comment by agx** [comment]
Any chance of getting official arm64 builds? That would also help a lot on Linux powered mobile phones, e.g. running https://github.com/PhoshMobi/phosh

**Comment by darkdragon-001** [comment]
> Anhy chance of getting official arm64 builds? That would also help a lot on Linux powered mobile phones, e.g. running https://github.com/PhoshMobi/phosh

I gave it a quick shot and OpenFst fails to built with the custom `Makefile`. I uploaded my setup in https://github.com/alphacep/vosk-server/pull/270 in case someone else wants to give it a try.

**Comment by darkdragon-001** [comment]
I could successfully build the image for arm64 with #270 now. Only a few small changes to the build system are necessary.

**Comment by darkdragon-001** [comment]
@agx in case you want to use openfst and openblas from debian instead of building from source, you can use the following for testing:
```Dockerfile
FROM debian:12

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  bzip2 \
  unzip \
  xz-utils \
  g++ \
  make \
  cmake \
  git \
  python3 \
  python3-dev \
  python3-websockets \
  python3-setuptools \
  python3-pip \
  python3-wheel \
  python3-cffi \
  zlib1g-dev \
  automake \
  autoconf \
  libtool \
  pkg-config \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  f2c \
  libfst-dev \
  libopenblas-pthread-dev \
  && rm -rf /var/lib/apt/lists/*

RUN \
  git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi \
  && cd /opt/kaldi \
  && cmake -DMATHLIB=OpenBLAS -DKALDI_BUILD_EXE=OFF -DKALDI_BUILD_TEST=OFF -DBUILD_SHARED_LIBS=ON . \
  && cmake --build . --target kaldi-base kaldi-online2 kaldi-rnnlm -- -j $(nproc) \
  && mkdir libs && find src -name '*.so' -exec mv -t libs/ {} +
ENV LD_LIBRARY_PATH=/opt/kaldi/libs

RUN \
  git clone https://github.com/alphacep/vosk-api /opt/vosk-api \
  && cd /opt/vosk-api/src \
  && OPENFST_ROOT=/usr OPENBLAS_ROOT=/usr KALDI_ROOT=/opt/kaldi USE_SHARED=1 make -j $(nproc) \
  && cd /opt/vosk-api/python \
  && python3 ./setup.py install
RUN \
  git clone https://github.com/alphacep/vosk-server /opt/vosk-server

ENV MODEL_VERSION=0.22
RUN mkdir /opt/vosk-model-en \
  && cd /opt/vosk-model-en \
  && wget -q http://alphacephei.com/kaldi/models/vosk-model-en-us-${MODEL_VERSION}.zip \
  && unzip vosk-model-en-us-${MODEL_VERSION}.zip \
  && mv vosk-model-en-us-${MODEL_VERSION} model \
  && rm -rf vosk-model-en-us-${MODEL_VERSION}.zip

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/vosk-model-en/model" ]
```

**Comment by agx** [comment]
Nice work! @darkdragon-001 I can confirm that builds fine. I then overlayed a some model files via Dockerfile.kaldi-en but when then starting the container I get:

```
~$ podman run vosk0-en
Traceback (most recent call last):
  File "/opt/vosk-server/websocket/./asr_server.py", line 11, in <module>
    from vosk import Model, SpkModel, KaldiRecognizer
  File "/usr/local/lib/python3.11/dist-packages/vosk-0.3.75-py3.11.egg/vosk/__init__.py", line 37, in <module>
    _c = open_dll()
         ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vosk-0.3.75-py3.11.egg/vosk/__init__.py", line 31, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library '/usr/local/lib/python3.11/dist-packages/vosk-0.3.75-py3.11.egg/vosk/libvosk.so': libkaldi-online2.so: cannot open shared object file: No such file or directory
```

I didn't look further yet. Did you get the server running?

**Comment by nshmyrev** [comment]
Not sure why are you doing that friends. There is pip package, you can simply install it, no need to build kaldi inside your docker.

https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-0.3.45-py3-none-manylinux2014_aarch64.whl

**Comment by darkdragon-001** [comment]
@agx Just to make sure, you built this for arm64 with BuildKit+qemu via `docker buildx build --platform linux/arm64` as described in #270? Or are you building directly on an arm64 device?

**Comment by agx** [comment]
I built natively on arm64 (binaries in the container also have the correct architecture)

**Comment by darkdragon-001** [comment]
@agx I was missing `LD_LIBRARY_PATH=/opt/kaldi/libs`. Can you try to add a layer setting this env?

FYI: I also updated https://github.com/alphacep/vosk-server/issues/147#issuecomment-4225157667 to contain the env and also a model.

**Comment by darkdragon-001** [comment]
> Not sure why are you doing that friends. There is pip package, you can simply install it, no need to build kaldi inside your docker.
> 
> https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-0.3.45-py3-none-manylinux2014_aarch64.whl

@nshmyrev Thanks for the hint!

This allows to simplify the `Dockerfile` for testing to:
```Dockerfile
FROM python:3

RUN \
  git clone https://github.com/alphacep/vosk-server /opt/vosk-server
RUN \
  cd /opt/vosk-server && \
  python3 -m pip install -r requirements.txt

ENV MODEL_VERSION=0.22
RUN mkdir /opt/vosk-model-en \
  && cd /opt/vosk-model-en \
  && wget -q http://alphacephei.com/kaldi/models/vosk-model-en-us-${MODEL_VERSION}.zip \
  && unzip vosk-model-en-us-${MODEL_VERSION}.zip \
  && mv vosk-model-en-us-${MODEL_VERSION} model \
  && rm -rf vosk-model-en-us-${MODEL_VERSION}.zip \
  && touch -h -r model . ..

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/vosk-model-en/model" ]
```
