### ISSUE TITLE
ERROR:websockets.server:Error in connection handler

### ISSUE THREAD

**Issue by ch930410** [alphacep/vosk-server#223]
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/lib/python3/dist-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/opt/vosk-server/websocket/./asr_server.py", line 38, in recognize
    message = await websocket.recv()
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
INFO:root:Connection from ('172.17.0.1', 37984)
INFO:root:Config {'sample_rate': 8000}
INFO:root:Connection from ('172.17.0.1', 37988)
INFO:root:Config {'sample_rate': 8000}
INFO:root:Connection from ('172.17.0.1', 37992)
INFO:root:Config {'sample_rate': 8000}
INFO:root:Connection from ('172.17.0.1', 37996)
INFO:root:Connection from ('172.17.0.1', 38000)

**Comment by nshmyrev** [comment]
Some client closes the connection. What is the issue exactly?

**Comment by ch930410** [comment]
after I click on the connection, I will give you an error like this
![image](https://user-images.githubusercontent.com/28522577/234508397-17ac0aec-e034-48a0-b7f8-5c62ac50bc1d.png)

**Comment by ch930410** [comment]
audio permissions are enabled.
![image](https://user-images.githubusercontent.com/28522577/234510604-4f2a1d43-f6ce-4881-b6c7-21cc6b089858.png)

**Comment by nshmyrev** [comment]
I see, you can not stream from localhost that is a chrome restriction. You need https connection.

**Comment by ch930410** [comment]
according to Google's official instructions, localhost is considered a security source on HTTP; I don't quite understand why this is the case; Thank you very much; I will deploy the project to the server and take a look;

**Comment by nshmyrev** [comment]
There is "chrome://flags/#unsafely-treat-insecure-origin-as-secure" i believe

https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins/

**Comment by ch930410** [comment]
I have already configured it, it's useless
