### ISSUE TITLE
Getting error: websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

### ISSUE THREAD

**Issue by mlcatinit** [alphacep/vosk-server#228]
Hello when I am trying to follow the example given in documentation to run Vosk-server using docker I get this error

(base) C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket>python ./test_microphone.py -u ws://localhost:2700
Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 200, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 122, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 68, in <module>
    asyncio.run(main())
  File "C:\ProgramData\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 65, in main
    await run_test()
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 28, in run_test
    async with websockets.connect(args.uri) as websocket:
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 323, in handshake
    status_code, response_headers = await self.read_http_response()
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 145, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

I first ran the code to initialize the docker container given in documentation 
docker run -d -p 2700:2700 alphacep/kaldi-en:latest

then ran code for test and also microphone but get the websockets.exceptions.InvalidMessage: did not receive a valid HTTP response error

**Comment by nshmyrev** [comment]
Your localhost is configured with ipv6 it seems. Try to use 127.0.0.1:2700 instead of localhost:2700 and it will work.

**Comment by mlcatinit** [comment]
Hello, I tried changing it and got the same error

logs:
(base) C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket>python ./test_microphone.py -u ws://127.0.0.1:2700
Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 200, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\http.py", line 122, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 68, in <module>
    asyncio.run(main())
  File "C:\ProgramData\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 65, in main
    await run_test()
  File "C:\Users\Fawaz Shaik\Demos\VOSK\vosk-server\websocket\test_microphone.py", line 28, in run_test
    async with websockets.connect(args.uri) as websocket:
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 323, in handshake
    status_code, response_headers = await self.read_http_response()
  File "C:\Users\Fawaz Shaik\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 145, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

**Comment by nshmyrev** [comment]
Try to run docker container without -d, maybe it exits due to error.

**Comment by mlcatinit** [comment]
I am getting the same error, could this be because I do not have 16 GB RAM? I am running it locally with 8 GB RAM

**Comment by nshmyrev** [comment]
What is the output when you start docker?

**Comment by mlcatinit** [comment]
Error was due to ram limitations, thank you. I will close this.
