### ISSUE TITLE
Getting this websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason error when trying to use index.html client_example 

### ISSUE THREAD

**Issue by mlcatinit** [alphacep/vosk-server#230]
Getting this error when using latest english model with Docker Desktop.

I started running the Docker image on Docker Desktop and got inference when using test_microphone.py but when trying to run clicking  Listen get this error in logs in Docker Desktop

websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

**Comment by nshmyrev** [comment]
You can check javascript console logs for details

**Comment by mlcatinit** [comment]
javascript colsole shows no error, when starting transcript. It worked once, but trying again gives no result, looking at docker console I get these error logs

2023-07-12 12:32:49 ERROR:websockets.server:Error in connection handler
2023-07-12 12:32:49 Traceback (most recent call last):
2023-07-12 12:32:49   File "/usr/lib/python3/dist-packages/websockets/server.py", line 191, in handler
2023-07-12 12:32:49     await self.ws_handler(self, path)
2023-07-12 12:32:49   File "/opt/vosk-server/websocket/./asr_server.py", line 70, in recognize
2023-07-12 12:32:49     await websocket.send(response)
2023-07-12 12:32:49   File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 555, in send
2023-07-12 12:32:49     await self.ensure_open()
2023-07-12 12:32:49   File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 803, in ensure_open
2023-07-12 12:32:49     raise self.connection_closed_exc()
2023-07-12 12:32:49 websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
