### ISSUE TITLE
websockets version of the docker image of vosk-server crashes with audio longer than 90s

### ISSUE THREAD

**Issue by danielmorse** [alphacep/vosk-server#249]
I'm trying to extract the phenom timings from a piece of audio using the latest version of the alphacep/kaldi-en docker image. Most of the clips I am doing this with are fine, but I'm finding that I get this error when I'm trying to extract the word timings from the longest piece of audio (98185ms long, the next longest is 85315ms)

```
kinigu-vosk         | ERROR:websockets.server:Error in connection handler
kinigu-vosk         | Traceback (most recent call last):
kinigu-vosk         |   File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 838, in transfer_data
kinigu-vosk         |     await asyncio.shield(self._put_message_waiter)
kinigu-vosk         | asyncio.exceptions.CancelledError
kinigu-vosk         | 
kinigu-vosk         | The above exception was the direct cause of the following exception:
kinigu-vosk         | 
kinigu-vosk         | Traceback (most recent call last):
kinigu-vosk         |   File "/usr/lib/python3/dist-packages/websockets/server.py", line 191, in handler
kinigu-vosk         |     await self.ws_handler(self, path)
kinigu-vosk         |   File "/opt/vosk-server/websocket/./asr_server.py", line 70, in recognize
kinigu-vosk         |     await websocket.send(response)
kinigu-vosk         |   File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 555, in send
kinigu-vosk         |     await self.ensure_open()
kinigu-vosk         |   File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 812, in ensure_open
kinigu-vosk         |     raise self.connection_closed_exc()
kinigu-vosk         | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by nshmyrev** [comment]
We do not support phoneme timings, feels like you are using some other codebase.

**Comment by danielmorse** [comment]
Sorry, I should have said "word" not phonems. I'm extracting the individual timings of works. 

I think this might be the same as https://github.com/python-websockets/websockets/issues/912

I think this is an issue with the ping/pong implementation of the websockets library I am using. When I added logging to the ping/pong code it seemed to fix it, which is odd. None the less, I don't think it's your end.

**Comment by nshmyrev** [comment]
Ok, let us know if you have other questions please!
