### ISSUE TITLE
Unable to open port 2700

### ISSUE THREAD

**Issue by gobindabd** [alphacep/vosk-server#60]
[root@centos-s-1vcpu-1gb-nyc1-01 ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alphacep/kaldi-en   latest              49d015e0e7f4        3 days ago          3.87GB
[root@centos-s-1vcpu-1gb-nyc1-01 ~]# docker run -it --rm alphacep/kaldi-en /bin/sh
# ls
asr_server.py  test.py  test.wav  test16k.wav  test_ffmpeg.py  test_microphone.py  test_words.py
# ls
asr_server.py  test.py  test.wav  test16k.wav  test_ffmpeg.py  test_microphone.py  test_words.py
# ./test.py test.wav
Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    hello('ws://localhost:2700'))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./test.py", line 8, in hello
    async with websockets.connect(uri) as websocket:
  File "/usr/lib/python3/dist-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/usr/lib/python3/dist-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 968, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 2700), [Errno 99] Cannot assign requested address

**Comment by nshmyrev** [comment]
You are trying to run the test within docker without the service I presume. Try to run docker as advised in the documentation and run the client outside.
