### ISSUE TITLE
Problems with italian language

### ISSUE THREAD

**Issue by Scient122** [alphacep/vosk-server#93]
The docker build for italian isn't included so I created the following file, named `Dockerfile.kaldi-it`:

```
FROM alphacep/kaldi-vosk-server:latest

ENV MODEL_VERSION 0.4
RUN mkdir /opt/vosk-model-it \
   && cd /opt/vosk-model-it \
   && wget -q https://alphacephei.com/vosk/models/vosk-model-small-it-${MODEL_VERSION}.zip \
   && unzip vosk-model-small-it-${MODEL_VERSION}.zip \
   && mv vosk-model-small-it-${MODEL_VERSION} model \
   && rm -rf vosk-model-small-it-${MODEL_VERSION}.zip

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/vosk-model-it/model" ]
```

Then i build it trough the unix command `sudo docker build -t alphacep/kaldi-it -f Dockerfile.kaldi-it .` and run it trough `sudo docker run -d -p 2700:2700 alphacep/kaldi-it:latest`.
But when I execute test.py the following exceptions rise up:

```
Traceback (most recent call last):
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./test.py", line 17, in hello
    print (await websocket.recv())
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/ludovico/.local/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

What should I do to fix this?

**Comment by nshmyrev** [comment]
Add

ENV VOSK_SAMPLE_RATE 16000

and make sure you stream 16khz files

**Comment by Scient122** [comment]
> Add
> 
> ENV VOSK_SAMPLE_RATE 16000
> 
> and make sure you stream 16khz files

Thanks, it worked but if I wanted to use 8khz input files for this model, what should I do?

**Comment by nshmyrev** [comment]
You have to train your own model, current doesn't support 8khz

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further issues.
